### ISSUE TITLE
Better understanding pre-commit hook and sphinxcontrib-apidoc

### ISSUE THREAD

**Issue by caldwellst** [OCHA-DAP/pa-aa-toolbox#14]
While exploring adding a [pre-commit hook to ensure that documentation could be re-built using Sphinx](https://github.com/thclark/pre-commit-sphinx), I came into some confusing errors surrounding the `sphinxcontrib.apidoc` extension. I've resolved them but was hoping to better understand *what is actually happening*. The simple addition to the `.pre-commit-config.yaml` file ws:

```
  - repo: https://github.com/thclark/pre-commit-sphinx
    rev: 0.0.1
    hooks:
      - id: build-docs
        args: ['--cache-dir', 'docs/build/doctrees', '--html-dir', 'docs/build/html', '--source-dir', 'docs/source']
        language_version: python3
```

However, upon commit, the following error ws generated:

```
Build Sphinx Docs........................................................Failed
- hook id: build-docs
- exit code: 1

Running Sphinx v4.2.0

Extension error:
Could not import extension sphinxcontrib.apidoc (exception: No module named 'sphinxcontrib.apidoc')
```

This was despite the fact that I could run either of these below to compile the documentation:

```
sphinx-build -b html -d docs/build/doctrees docs/source docs/build/html
```
or
```
python setup.py build_sphinx
```
The first example is what was being called through the pre-commit hook.

Now, clearly the error message indicated that that the `sphinxcontrib-apidoc` extension was missing, so I just simply added that to `additional_dependencies`.

```
  - repo: https://github.com/thclark/pre-commit-sphinx
    rev: 0.0.1
    hooks:
      - id: build-docs
        additional_dependencies:
          - sphinxcontrib-apidoc
        args: ['--cache-dir', 'docs/build/doctrees', '--html-dir', 'docs/build/html', '--source-dir', 'docs/source']
        language_version: python3
```

This worked. However, I don't understand exactly why this was an issue in the first place. Essentially, what's the difference between what was being run through pre-commit versus directly calling the documentation building that meant it couldn't find the dependencies? Is each section in `.pre-commit-config.yaml` essentially run in its own separate environment? Why were other extensions not required to be listed?

Was wondering if @turnerm or @mcarans you might have any insights?
